[package]
name = "bexa-ui-render"
version = "0.1.0"
edition = "2024"

[dependencies]
bexa-ui-core = { path = "../bexa-ui-core" }
bytemuck = { version = "1.14", features = ["derive"] }
glyphon = "0.10.0"
pollster = "0.3"
taffy = "0.4"
wgpu = { version = "28", features = ["wgsl"] }
winit = "0.29"
