[package]
name = "bexa-ui"
version = "0.1.0"
edition = "2024"

[features]
default = []
terminal = ["bexa-ui-core/terminal"]

[dependencies]
bexa-ui-core = { path = "../bexa-ui-core" }
bexa-ui-render = { path = "../bexa-ui-render" }
